edsdme/blocks/announcements/AnnouncementsCards.js
edsdme/blocks/announcements/announcements.js
edsdme/components/PartnerCards.js
edsdme/components/PartnerCardsStyles.js
edsdme/scripts/scripts.js
edsdme/scripts/utils.js

Resolves: [MWPW-147192](https://jira.corp.adobe.com/browse/MWPW-147192)
**LINKS:**
**Before:** https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements
**After:** https://mwpw-147192-announcements-cards--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements
**DE locale before:** https://stage--dme-partners--adobecom.hlx.page/de/channelpartners/drafts/dragana/announcements
**De locale after:** https://mwpw-147192-announcements-cards--dme-partners--adobecom.hlx.page/de/channelpartners/drafts/dragana/announcements
NOTE: This is the initial state, component will be updated with new requirements

MWPW-147192 - Announcements cards component

---

edsdme/scripts/scripts.js

- https://partners.stage.adobe.com/edsdme/partners-shared/placeholders.json

contentRoot update

---

edsdme/blocks/announcements/AnnouncementsCards.js
edsdme/blocks/announcements/announcements.js
edsdme/components/NewsCard.js
edsdme/components/PartnerCards.js
edsdme/components/PartnerCardsStyles.js
edsdme/scripts/utils.js
test/blocks/announcements/announcements.test.js

Resolves: [MWPW-147192](https://jira.corp.adobe.com/browse/MWPW-147192)
- added **_announcements - archive_** variation of the block
- tag _**caas:adobe-partners/collections/announcements/never-expires**_ will be active in a few days
- refactored code (moved common elements to utils, moved NewsBlock class to a separate file)
- fixed eslint errors
- just preview for providing multiple block templates for block with preconfigured tags - will be updated with real tags) https://adobe.sharepoint.com/:w:/r/sites/AdobePartnerConnectionAPC35/_layouts/15/Doc.aspx?sourcedoc=%7BACEC75C2-E3A2-43D3-84F8-C6A1A133447E%7D&file=announcements.docx&action=default&mobileredirect=true&wdsle=0
- removed the options that made no sense from the date filter; the filter will we updated with a date picker in …

Mwpw 147192 announcements date filter

---

edsdme/components/PartnerCards.js
edsdme/scripts/utils.js

**Resolves:** [MWPW-153222](https://jira.corp.adobe.com/browse/MWPW-153222)
- Optimisation changes from https://github.com/adobecom/dx-partners/pull/38 are used
- If the user is logged in, the permissionRegion from the cookie is used for the tag, otherwise a worldwide tag will be passed
**LINKS:**
**Before:**
- https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements-archive
- https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements
**After:**
- https://mwpw-153222-region-level-limit--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements-archive
- https://mwpw-153222-region-level-limit--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements

MWPW - 153222 - region level limit

---

edsdme/components/PartnerCards.js

**Resolves:** [MWPW-156079](https://jira.corp.adobe.com/browse/MWPW-156079)
- sorting options work properly
**LINKS:**
**Before:** https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements
After: https://mwpw-156079-sorting-fix--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements

MWPW-156079 - sorting options fix

---

.github/workflows/run-nala-on-dme.yml

DRAFT since we need to add the secret - have to check with @zagi25 where we can do that
- adds HLX_API_KEY environment variable

MWPW-156606 - protect .page and .live sites

---

edsdme/components/PartnerCardsStyles.js

**Resolves:** [MWPW-157064](https://jira.corp.adobe.com/browse/MWPW-157064)
**LINKS:**
- **Before**: https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements?georouting=off
- **After**: https://mwpw-157064-sort-behind-profile-drop--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements?georouting=off

MWPW-157064 - sort drop behind profile drop

---

nala/blocks/banners/banners.page.js
nala/blocks/banners/banners.spec.js
nala/blocks/banners/banners.test.js
nala/blocks/signin/signin.page.js

This PR contains nala tests for renew banners.
Test cases are defined here: [Banners test cases](https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=WEBT&title=Banners)

New: added tests for banners

---

edsdme/blocks/partners-navigation/partners-navigation.js
edsdme/scripts/personalization.js

Resolves: [MWPW-157623](https://jira.corp.adobe.com/browse/MWPW-157623)
Before: https://stage--dme-partners--adobecom.hlx.live/channelpartners/home/?georouting=off
After: https://mwpw-157623-gnav-not-rendered-firefox--dme-partners--adobecom.hlx.live/channelpartners/home/?georouting=off

MWPW-157623: Fix gnav rendering issue in firefox

---

edsdme/scripts/scripts.js
edsdme/scripts/utils.js

- Add query param to ims redirect url when user is not signed in
Resolves: [MWPW-158046](https://jira.corp.adobe.com/browse/MWPW-158046)
Before: https://stage--dme-partners--adobecom.hlx.live/channelpartners/
After: https://mwpw-158046-redirect-after-login--dme-partners--adobecom.hlx.live/channelpartners/

MWPW-158046: Add query param to ims redirect url

---

edsdme/blocks/partners-navigation/features/profile/dropdown.css
edsdme/blocks/partners-navigation/features/profile/dropdown.js
edsdme/blocks/partners-navigation/partners-navigation.css
edsdme/blocks/partners-navigation/partners-navigation.js
edsdme/blocks/partners-navigation/utilities/utilities.js

Resolves: [MWPW-157753](https://jira.corp.adobe.com/browse/MWPW-157753)
Before: https://partners.stage.adobe.com/channelpartners/home/#
After: https://mwpw-157753-dropdown-improvements--dme-partners--adobecom.hlx.live/channelpartners/

MWPW-157753 - make only edit profile anchor clickable

---

nala/blocks/signin/signin.test.js

increase timeout for sign in test on firefox, and removing # form url

---

nala/blocks/signin/signin.page.js
nala/blocks/signin/signin.spec.js
nala/blocks/signin/signin.test.js

Fixing firefox tests

---

.github/workflows/run-nala-on-dme.yml

Nala test are executed only once and only when:
- PR is created with run-on-dme label or the label was added later
- PR was updated and it has `run-on-dme` label
- PR was reopened and it has `run-on-dme` label
There is no more need to add @anonymous label to the PR to trigger nala tests.

Fix nala action

---

edsdme/components/PartnerCards.js

**Resolves:** [MWPW-160143](https://jira.corp.adobe.com/browse/MWPW-160143)
**Links:**
**Before:** https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements?filters=yes&audience=sales&georouting=off
**After:** https://mwpw-160143-arbitrary-fix--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements?filters=yes&audience=sales&georouting=off

MWPW-160143 - arbitrary fix

---

edsdme/blocks/partners-navigation/features/profile/dropdown.js
edsdme/blocks/partners-navigation/utilities/utilities.js

Resolves: [MWPW-157752](https://jira.corp.adobe.com/browse/MWPW-157752)
Before: https://stage--dme-partners--adobecom.hlx.live/channelpartners/
After: https://mwpw-157752-porfile-dropdown-close--dme-partners--adobecom.hlx.live/channelpartners/

MWPW-157752: Close profiled dropdown when clicking outside

---

edsdme/scripts/scripts.js
edsdme/scripts/utils.js
test/scripts/utils.jest.js

Resolves: [MWPW-160441](https://jira.corp.adobe.com/browse/MWPW-160441)
Before: https://stage--dme-partners--adobecom.hlx.live/channelpartners/?akamaiLocale=us
After: https://mwpw-160441-prevent-geo-popup--dme-partners--adobecom.hlx.live/channelpartners/?akamaiLocale=us

MWPW-160441: Disable geo popup for milo pages

---

edsdme/blocks/partners-navigation/features/search/gnav-search.css
edsdme/blocks/partners-navigation/features/search/gnav-search.js
edsdme/blocks/partners-navigation/partners-navigation.js
edsdme/components/PartnerCards.js

https://jira.corp.adobe.com/browse/MWPW-154138
**Note:** A suggestions list update will follow in a subsequent PR
- fixes gnav search module imports
- supports search term reading in partner card url params
- adjusts search placeholders
- adds correct search link
- adds view all results link and styles it
before: https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/richard/gnavsearch
now: https://feat-mwpw-154138-gnav-search-ui--dme-partners--adobecom.hlx.page/channelpartners/drafts/richard/gnavsearch

MWPW-154138 - gnav search UI

---

nala/region-selectors/region-selectors.page.js
nala/region-selectors/region-selectors.spec.js
nala/region-selectors/region-selectors.test.js

After: [https://mwpw-160655-region-selector-tests--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off](https://mwpw-160655-region-selector-tests--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off)

New: added region selector tests

---

edsdme/components/SearchCard.js

after: https://MWPW-161560-remove-html-size--dme-partners--adobecom.hlx.page/channelpartners/home/search/?georouting=off

Mwpw 161560 remove html size

---

edsdme/components/SearchCard.js
edsdme/img/icons/default.svg

after: https://MWPW-162002-filetypes--dme-partners--adobecom.hlx.page/channelpartners/home/search/?georouting=off

MWPW-1162002-filetypes download/preview restrictions, default file type

---

edsdme/blocks/announcements-preview/announcements-preview.css

removing underline on title and description on announcement preview component
URL for testing: https://removing-underline--dme-partners--adobecom.hlx.page/channelpartners/drafts/tijana/wip/announcements-preview

removing underline 

---

edsdme/blocks/search/SearchCards.js

after: https://MWPW-162737-fix-dialog-closing-issue--dme-partners--adobecom.hlx.page/channelpartners/home/search/?georouting=off

MWPW-162737-update selector based on updated html

---

edsdme/scripts/personalization.js

Resolves: [MWPW-163199](https://jira.corp.adobe.com/browse/MWPW-163199)
Before: https://stage--dme-partners--adobecom.hlx.live/na/channelpartners/drafts/ben/test-section-segmentation-copy
After: https://mwpw-163199-fragments-personalization--dme-partners--adobecom.hlx.live/na/channelpartners/drafts/ben/test-section-segmentation-copy

MWPW-163199: Hide fragments in personalized sections

---

edsdme/components/SearchCard.js
package-lock.json
package.json

Resolves: [MWPW-163223](https://jira.corp.adobe.com/browse/MWPW-163223)
Before: https://stage--dme-partners--adobecom.hlx.live/channelpartners/home/search/
After: https://mwpw-163223-pdf-icon-missing--dme-partners--adobecom.hlx.live/channelpartners/home/search/

MWPW-163223: Fixed pdf icon missing

---

edsdme/blocks/partners-navigation/utilities/utilities.js

Resolves: [MWPW-163704](https://jira.corp.adobe.com/browse/MWPW-163704)
Before: https://stage--dme-partners--adobecom.hlx.live/channelpartners/
After: https://mwpw-163704-hidden-gnav--dme-partners--adobecom.hlx.live/channelpartners/

MWPW-163704: Fix gnav css imports

---

edsdme/components/PartnerCards.js

Resolves: [MWPW-162360](https://jira.corp.adobe.com/browse/MWPW-162360)
Before: https://stage--dme-partners--adobecom.hlx.live/channelpartners/home/search/
After: https://mwpw-162360-search-filter--dme-partners--adobecom.hlx.live/channelpartners/home/search/

MWPW-162360: Fixed 'filter' query bug

---

edsdme/blocks/announcements-preview/announcements-preview.js
edsdme/blocks/logos/LogosCards.js
edsdme/components/PartnerCards.js

Restrict announcements to current site
eslint fix for search-full in path
Ticket: https://jira.corp.adobe.com/browse/MWPW-163708
testing url: 
https://stage--dme-partners--adobecom.hlx.page/es/channelpartners/home/
https://mwpw-163708-filter-cards-by-site--dme-partners--adobecom.hlx.page/apac/channelpartners/drafts/tijana/announcements-preview

MWPW-163708-filter-cards-by-site

---

edsdme/blocks/announcements-preview/announcements-preview.js

Resolves: [MWPW-163598](https://jira.corp.adobe.com/browse/MWPW-163598)
Before: https://stage--dme-partners--adobecom.hlx.live/apac/channelpartners/drafts/ratko/announcements-preview
After: https://mwpw-163598-announcment-preview-link--dme-partners--adobecom.hlx.live/apac/channelpartners/drafts/ratko/announcements-preview

MWPW-163598: Format links so they point to correct domain

---

edsdme/blocks/partners-navigation/features/search/gnav-search.js

test url:
- https://mwpw-164349-get-full-search-term--dme-partners--adobecom.hlx.page/na/channelpartners/home/

MWPW-164349-on enter read value from input

---

edsdme/scripts/scripts.js

test url:
https://MWPW-164391-cbc-logged-in--dme-partners--adobecom.hlx.page/na/channelpartners/home/

MWPW-164391-rewrite links only if user is singed in

---

edsdme/blocks/announcements-preview/announcements-preview.css
edsdme/blocks/announcements-preview/announcements-preview.js

testing url: 
https://mwpw-164346-preview--dme-partners--adobecom.hlx.live/channelpartners/drafts/tijana/wip/announcements-preview 
ticket: [MWPW-164346](https://jira.corp.adobe.com/browse/MWPW-164346)

Align Announcement Preview with Milo Blocks

---

edsdme/scripts/rewriteLinks.js
edsdme/scripts/scripts.js
test/scripts/rewriteLinks.jest.js

test url:
https://mwpw-164391-rewrite-domain--dme-partners--adobecom.hlx.page/na/channelpartners/home/

Mwpw 164391 rewrite domain

---

edsdme/blocks/search-full/SearchCardsStyles.js

fixing filter display on Search component for smaller screen sizes
related to ticket https://jira.corp.adobe.com/browse/MWPW-165153
testing urls: https://search-viewpoint-fix--dme-partners--adobecom.hlx.page/channelpartners/home/search/

fix search viewpoints

---

edsdme/blocks/partners-navigation/partners-navigation.css

Testing URL: https://mwpw-165157-button-hover-fix--dme-partners--adobecom.hlx.page/channelpartners/

MWPW-165157-Text is not visible when hover over button in Gnav

---

edsdme/styles/styles.css

Testing URL: https://mwpw-162386--dme-partners--adobecom.hlx.page/channelpartners/

MWPW-162386-Font styles are different on Firefox vs. Chrome on the search page title

---

edsdme/blocks/partners-navigation/features/profile/dropdown.js
edsdme/scripts/utils.js

Testing URL: https://mwpw-165470--dme-partners--adobecom.hlx.page/channelpartners/

MWPW-165470-remove the term after logging out

---

edsdme/components/SinglePartnerCard.js

- also allow tranformation for card prod links
resolves: https://jira.corp.adobe.com/browse/MWPW-165933
test url:
[https://MWPW-165933-announcement-links-prod--dme-partners--adobecom.hlx.live/na/channelpartners/home/announcements/](https://MWPW-165933-announcement-links-prod--dme-partners--adobecom.hlx.live/na/channelpartners/home/announcements/)

MWPW-165933 - announcements links point to stage

---

edsdme/components/SearchCard.js
edsdme/scripts/utils.js

Tickets: [MWPW-165926](https://jira.corp.adobe.com/browse/MWPW-165926), [MWPW-165925](https://jira.corp.adobe.com/browse/MWPW-165925)
use replaceText on each tag to get the value from placeholders
preload placeholders for blocks we use them
Testing urls: 
https://mwpw-165925-fix-tags-logic--dme-partners--adobecom.hlx.page/channelpartners/home/marketing/logos/
https://mwpw-165925-fix-tags-logic--dme-partners--adobecom.hlx.page/channelpartners/home/search/

replace tags with placeholder value

---

edsdme/scripts/rewriteLinks.js
test/scripts/rewriteLinks.jest.js

https://jira.corp.adobe.com/browse/MWPW-163288
- moves domain map configuration inside domain configs
- adds stage path mappings config per domain to rewrite paths
- updates sales center stage mappings
- updates and adds to stage test case
Test URL:
https://mwpw-163288-sales-center-rewrites--dme-partners--adobecom.hlx.page/channelpartners/

MWPW-163288 - rewrite sales center links

---

edsdme/styles/styles.css

https://mwpw-166658-personalize-fragments--dme-partners--adobecom.hlx.live/channelpartners/drafts/ben/index-copy

MWPW-166658: add !important

---

edsdme/blocks/partners-navigation/utilities/utilities.js

Test URL:
https://mwpw-166846-adobe-icon--dme-partners--adobecom.hlx.page/channelpartners/

MWPW-166846 - replace adobe icon

---

nala/blocks/profile-dropdown/profile-dropdown.spec.js
nala/blocks/region-selectors/region-selectors.spec.js
nala/blocks/signin/signin.spec.js
nala/blocks/signin/signin.test.js

Nala test fix spanihs translation

---

edsdme/scripts/utils.js
test/scripts/utils.jest.js

https://jira.corp.adobe.com/browse/MWPW-167024
- maps en-GB to en-US
Test URL:
https://MWPW-167024-announcements-emea--dme-partners--adobecom.hlx.page/channelpartners/home/announcements/

MWPW-167024 - Announcements are not displayed for Emea site

---

nala/blocks/smoke-test/smoke.page.js

URL for testing: https://smoke-search-page-fix--dme-partners--adobecom.hlx.page/channelpartners/

search-page-fix

---

tools/sidekick/config.json

Test url:
https://MWPW-167115-hlx4--dme-partners--adobecom.hlx.page/channelpartners/home/

mwpw-167115-prepare for config migration (to keep hlx4 in sidekick)

---

tools/sidekick/config.json

Test url : https://mwpw-167115-hlx4-config--dme-partners--adobecom.hlx.page/channelpartners/

MWPW-167115-sidekick config

---

nala/blocks/signin/signin.spec.js
nala/blocks/signin/signin.test.js

Testing URL: https://mwpw-166718--dme-partners--adobecom.hlx.page/channelpartners/

MWPW-166718: [Automation][MAPC] Create nala tests to check if abandoned user is redirected to adobe account menagement

---

nala/utils/global.setup.js

Test url:
https://fix-tests--dme-partners--adobecom.aem.page/channelpartners/home/

use existing page

---

edsdme/components/SearchCard.js

https://jira.corp.adobe.com/browse/MWPW-162728
- fixes download and preview show logic for announcements
URL: https://mwpw-162728-announcements-fix--dme-partners--adobecom.aem.page/channelpartners/home/search/

MWPW-162728 - Announcements should have separate icon

---

nala/blocks/smoke-test/smoke.page.js
nala/blocks/smoke-test/smoke.test.js

url:  https://cal-smoke-test-fix--dme-partners--adobecom.aem.page/channelpartners/ 

Cal smoke test fix

---

nala/blocks/announcements/announcements.test.js

Testing URL: https://fix-announcement-page-timeout--dme-partners--adobecom.aem.page/channelpartners/ 

fix-announcement-page-timeout

---

nala/blocks/announcements/announcements.page.js
nala/blocks/announcements/announcements.test.js

Testing URL: https://fix-announcement-page-timeout--dme-partners--adobecom.aem.page/channelpartners/ 

fix-announcement-tests-timeout

---

nala/blocks/signin/signin.page.js
nala/blocks/signin/signin.test.js

url: https://release-tests-fix--dme-partners--adobecom.aem.page/channelpartners/ 

release-tests-fix

---

edsdme/blocks/announcements/AnnouncementsCards.js
edsdme/components/PartnerCards.js
edsdme/components/PartnerCardsStyles.js

https://jira.corp.adobe.com/browse/MWPW-162732
- adds counter to mobile list items
- adds list of chosen filters in mobile view
- also apply to announcement cards
Test URLs:
* https://mwpw-162732-filter-counter--dme-partners--adobecom.aem.page/channelpartners/home/search/
* https://mwpw-162732-filter-counter--dme-partners--adobecom.aem.page/channelpartners/home/announcements/

MWPW-162732 - counter for selected filters on mobile

---

nala/blocks/announcements/announcements.test.js

Testing URL: https://fix-announcement-page-timeout--dme-partners--adobecom.aem.page/channelpartners/ 

updating rest of the announcement tests

---

edsdme/blocks/announcements/announcements.js
edsdme/blocks/search-full/search-full.js
edsdme/components/PartnerCards.js
edsdme/components/PartnerCardsStyles.js

Test url:
https://MWPW-162731-hide-filters--dme-partners--adobecom.aem.live/channelpartners/drafts/sonja/search-filters/document

Mwpw 162731 hide filters

---

nala/blocks/banners/banners.spec.js

url: https://include-banners-tests--dme-partners--adobecom.aem.page/channelpartners/

include-banners-test

---

edsdme/scripts/personalization.js
edsdme/scripts/personalizationConfig.js

ticket: https://jira.corp.adobe.com/browse/MWPW-172016
testing url:
https://mwpw-172016--dme-partners--adobecom.aem.live/channelpartners/

code sync for gnav and page personalization

---

nala/blocks/smoke-test/smoke.page.js
nala/blocks/smoke-test/smoke.spec.js
nala/blocks/smoke-test/smoke.test.js

Testing URL: https://mwpw-164352--dme-partners--adobecom.aem.page/channelpartners/

MWPW-164352: [Automation] [MAPC] - Implement test cases for SSO integration

---

nala/blocks/smoke-test/smoke.page.js
nala/blocks/smoke-test/smoke.spec.js
nala/blocks/smoke-test/smoke.test.js

Testing URL: https://mwpw-163602--dme-partners--adobecom.aem.live/channelpartners/

MWPW-163602: [Automation][MAPC] Implement test for Partner/Distributor Finder

---

edsdme/blocks/partners-navigation/utilities/menu/menu.js
edsdme/scripts/personalization.js

testing url: https://MWPW-172016-sync-update--dme-partners--adobecom.aem.page/channelpartners/

MWPW-172016-sync-update

---

edsdme/scripts/utils.js

Test url:
https://mwpw-171378-banner-date-fix--dme-partners--adobecom.aem.live/channelpartners/drafts/automation/regression/protected-home

MWPW-171378: setting hours to midnight, change rounding up days

---

edsdme/scripts/scripts.js

Testing-URL: https://mwpw-172830-ims-env--dme-partners--adobecom.aem.live/channelpartners/

MWPW-172830: set milo/ims env

---

nala/blocks/smoke-test/smoke.page.js
nala/blocks/smoke-test/smoke.spec.js
nala/blocks/smoke-test/smoke.test.js

Test URL: https://mwpw-173299--dme-partners--adobecom.hlx.live/channelpartners/

MWPW-173299: [Automation][MAPC] Implement tests for loading correct footer and gnav based on locale

---

edsdme/blocks/utils/utils.js
edsdme/scripts/utils.js

URL for testing: 
- https://mwpw-172830-update-utils--dme-partners--adobecom.aem.live/channelpartners/home/

MWPW-172830: Improve error handling and user messaging

---

edsdme/blocks/utils/utils.js
edsdme/scripts/scripts.js
edsdme/scripts/utils.js

Testing Url: https://mwpw-172830-enable-stage--dme-partners--adobecom.aem.live/channelpartners/drafts/illya/announcements/to-translate#

MWPW-172830: improve UX, enable testing from stage--dme-partners--adobecom.aem.live

---

edsdme/blocks/utils/utils.js

waiting for pages to be previewed and published before calling runtime action
waiting for sidekick to load to set event for publishing
Testing url: 
https://poll-sidekick-and-responses--dme-partners--adobecom.aem.live/channelpartners/

waiting for pages to be previewed and published

---

edsdme/blocks/dme-form/dme-form.css
edsdme/blocks/dme-form/dme-form.js
nala/blocks/redirects/redirects.test.js

Test URL: https://mwpw-174792--dme-partners--adobecom.hlx.page/channelpartners/drafts/slobodanka/promo-pricing-rebate-request-form

MWPW-174792: APC | Promo Pricing Rebate Request Form

---

edsdme/blocks/dme-form/dme-form.js

Test URL: https://mwpw-174792--dme-partners--adobecom.hlx.page/channelpartners/drafts/slobodanka/promo-pricing-rebate-request-form

Field and Type values formatting update

---

nala/blocks/pricelist-page/pricelist.page.js
nala/blocks/pricelist-page/pricelist.spec.js
nala/blocks/pricelist-page/pricelist.test.js
nala/blocks/protected-content/protected-content.test.js
nala/blocks/search-page/search.page.js
nala/blocks/search-page/search.test.js
nala/blocks/signin/signin.page.js
nala/blocks/signin/signin.spec.js
nala/blocks/signin/signin.test.js
nala/blocks/smoke-test/smoke.page.js

test url: https://new-update-for-tests--dme-partners--adobecom.aem.page/channelpartners/

tests-improvement

---

nala/blocks/smoke-test/smoke.page.js
nala/blocks/smoke-test/smoke.spec.js
nala/blocks/smoke-test/smoke.test.js

Test URL: https://stage--dme-partners--adobecom.aem.live/channelpartners/

MAPC 25.15

---

nala/blocks/accessing-assets/accessing-assets.spec.js
nala/blocks/banners/banners.page.js
nala/blocks/banners/banners.test.js
nala/blocks/pricelist-page/pricelist.spec.js
nala/blocks/protected-content/protected-content.test.js
nala/blocks/signin/signin.page.js
nala/blocks/smoke-test/smoke.page.js

Test url: https://bracnh-with-dme-fixes--dme-partners--adobecom.aem.page/channelpartners/ 

Branch with dme fixes

---

edsdme/blocks/pricelist/PricelistBlock.js
edsdme/blocks/utils/utils.js
edsdme/components/SearchCard.js

- work around for spectrum web components issue https://github.com/adobe/spectrum-web-components/issues/5749
- remove download query param as it's unnecessary
Testing URL: https://mwpw-178382-download-links--dme-partners--adobecom.aem.live/channelpartners/home/search/

MWPW-178382: Download Links
