adobecom/dme-partners

edsdme/blocks/announcements/AnnouncementsCards.js

**Resolves**: [MWPW-147192](https://jira.corp.adobe.com/browse/MWPW-147192)
- if the card is not older then 180 days, but the eventEnd date is in the past, it will be displayed in Announcements archive and hidden from the Announcements component
**Quick summary:**
- Cards displayed in the **_Announcements archive_** are those not tagged with 'never-expires', and either older than 180 days or with an eventEnd date in the past.
- Cards displayed in **_Announcements_** are those tagged with 'never-expires', or not older than 180 days with an eventEnd date that is not in the past.
**LINKS:**
**Announcements:**
Before: https://stage--dme-partners--adobecom.hlx.live/channelpartners/drafts/kristijan/announcements
After: https://mwpw-147192-old-events-hidden-announce--dme-partners--adobecom.hlx.li …

MWPW-147192 - card with old event hidden from Announcements

---

edsdme/scripts/scripts.js
edsdme/scripts/utils.js

Features:
- Added logout feature, logout redirect url is set based on `adobe-target-after-logout` meta tag, or is set to home page of the program if meta tag is not defined
- Moved `adobe-target-after-login` logic from runtime to MILO. Instead of defining this value in headers, now it will be defined in meta data of the page. If meta tag is defined, IMS will redirect user to that page after login, if it is not defined user will be redirected back to the page where he started the login process
- If `adobe-target-after-login` is defined and user is already logged in, user will be sent to the page that is defined in `adobe-target-after-login`
Resolves: [MWPW-153924](https://jira.corp.adobe.com/browse/MWPW-153924)
Test URLs:
- Before: …

MWPW-153924: Implement logout logic

---

edsdme/components/NewsCard.js
edsdme/components/PartnerCardsStyles.js

- checks news card background image on first updated
- replace with a default image located at 
- STAGE: https://partners.stage.adobe.com/content/dam/solution/en/images/card-collection/sample_default.png
- PROD: https://partners.adobe.com/content/dam/solution/en/images/card-collection/sample_default.png
**Before:**
- https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements
**After:**
- https://mwpw-155065-invalid-thumbnail-fallback--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/announcements

MWPW-155065 PartnerCards fallback for invalid thumbnail images

---

edsdme/components/PartnerCards.js

**Resolves:** [MWPW-156066](https://jira.corp.adobe.com/browse/MWPW-156066)
- PR for not displaying empty elements when for filters/sort items are authored empty bullets
**LINKS:**
**Before:** https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/kristijan/announcements-author-test
**After:** https://mwpw-156066-authored-empty-li--dme-partners--adobecom.hlx.page/channelpartners/drafts/kristijan/announcements-author-test

MWPW-156066 - do not display empty li el as sort/filter item

---

edsdme/scripts/utils.js

**Resolves:** [MWPW-155099](https://jira.corp.adobe.com/browse/MWPW-155099)
**LINKS:**
**Before:**https://stage--dme-partners--adobecom.hlx.page/channelpartners/?georouting=off
**After:** https://mwpw-155099-renew-banner-update--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off

MWPW-155099 - renew banner update

---

edsdme/blocks/announcement-date/announcement-date.css
edsdme/blocks/announcement-date/announcement-date.js
edsdme/blocks/announcements/announcements.js
edsdme/blocks/search/SearchCards.js
edsdme/components/PartnerCards.js
edsdme/components/SearchCard.js
edsdme/components/SinglePartnerCard.js
edsdme/scripts/utils.js
edsdme/styles/styles.css
test/blocks/announcement-date/announcement-date.test.js
test/blocks/announcement-date/mocks/body.html

[MWPW-154151](https://jira.corp.adobe.com/browse/MWPW-154151)
- adds an announcement date block that reads the created date of the card metadata if present and displays it
- adds an `announcement-title` style for the divider
- adds localization in date formatting utility and updates references
- adds unit tests
**LINKS:**
- **Before**: https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/richard/announcements-template?georouting=off
- **After**: https://mwpw-153151-announcement-date--dme-partners--adobecom.hlx.page/channelpartners/drafts/richard/announcements-template?georouting=off

MWPW-154151 announcement template date block

---

edsdme/blocks/announcement-date/announcement-date.css
edsdme/styles/styles.css

ticket: https://jira.corp.adobe.com/browse/MWPW-154151
design: https://xd.adobe.com/view/125460f4-a964-49d0-9571-c08ae19e77fe-4707/screen/2e2c842b-f904-4ee5-8622-4f80dddf3e04
- moves line rendering to announcement date for simplified authoring
- uses css variables
- authoring proposal for the announcement back button is in the [announcement template document](https://adobe.sharepoint.com/:w:/r/sites/AdobePartnerConnectionAPC35/_layouts/15/Doc.aspx?sourcedoc=%7BAED2930A-DBD2-4C64-A1FB-D903B5F315D1%7D&file=announcements-template.docx&action=default&mobileredirect=true)
- icon currently missing since it needs adding in Milo
**LINKS:**
- **Before**: https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/richard/announcements-template?georouting=off
- **After**: …

MWPW-154151 announcement template back button

---

edsdme/scripts/utils.js
test/scripts/utils.jest.js

- Load gnav/footer with locale prefix if metadata is authored without locale (eg. `/edsdme/partners-shared/footer`)
Resolves: [MWPW-159126](https://jira.corp.adobe.com/browse/MWPW-159126)
Before: https://stage--dme-partners--adobecom.hlx.page/de/channelpartners/drafts/ratko/test
After: https://mwpw-159126-gnav-footer-locale--dme-partners--adobecom.hlx.page/de/channelpartners/drafts/ratko/test

MWPW-159126: Load gnav/footer based on locale

---

nala/blocks/popups/popups.page.js
nala/blocks/popups/popups.spec.js
nala/blocks/popups/popups.test.js

After: [https://MWPW-159124-geo-pop-up-tests--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off](https://MWPW-159124-geo-pop-up-tests--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off)

New: added geo pop-up tests

---

nala/blocks/popups/popups.spec.js

After: [https://quickfix-popups-tests--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off](https://quickfix-popups-tests--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off)

Disabled popups tests due to timeouts

---

edsdme/blocks/search/SearchCards.js
edsdme/components/PartnerCards.js

before:
https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/search
after: https://mwpw-160266-integrate-search-api--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/search?georouting=off

MWPW-160266-integrate search api

---

nala/blocks/popups/popups.spec.js
nala/blocks/popups/popups.test.js

After: [https://geo-popup-tests-fix--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off](https://geo-popup-tests-fix--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off)
**Important note:** Geo pop-up tests could not be ran on the feature branches due to vpn. Since all the tests depend on partners.stage.adobe.com, tests will be ran on the circleCi instead.

Fix: tests adjusted to run on circle ci

---

edsdme/blocks/partners-navigation/features/search/gnav-search.js

- updates suggestions in global nav search to use AIO endpoint
before: https://stage--dme-partners--adobecom.hlx.page/channelpartners/drafts/richard/gnavsearch
now: https://feat-mwpw-154138-gnav-search-ui--dme-partners--adobecom.hlx.page/channelpartners/drafts/richard/gnavsearch

MWPW-154138 - gnav search

---

edsdme/scripts/scripts.js

Added APC configs for AEP (Analytics)
Before:
https://partners.stage.adobe.com/channelpartners/
After:
https://mwpw-147197-aep--dme-partners--adobecom.hlx.live/channelpartners/
Check `window.marketingtech.adobe.alloy.edgeConfigId`

AEP config

---

edsdme/blocks/partners-navigation/features/search/gnav-search.js
edsdme/blocks/search/SearchCards.js

- include credentials for passing cookies to runtime action
after: https://mwpw-159508-search-middle-layer--dme-partners--adobecom.hlx.page/channelpartners/home/search/

MWPW-159508 - search middle layer

---

edsdme/blocks/search/SearchCards.js

after: https://MWPW-154152-remove-authorization-header--dme-partners--adobecom.hlx.page/channelpartners/home/search/?georouting=off

MWPW-154152-remove authorization header since it is not supporeted

---

nala/blocks/region-selectors/region-selectors.page.js

Selector for the change region pop-up has been updated.
After: [https://region-selector-fix--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off](https://region-selector-fix--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off)

Fix: selector for the change region pop-up changed

---

edsdme/blocks/partners-navigation/partners-navigation.js
edsdme/scripts/links.js
edsdme/scripts/personalization.js
test/scripts/links.jest.js

Resolves: [MWPW-163532](https://jira.corp.adobe.com/browse/MWPW-163532)
- adds links script for rewriting single link hrefs based on prod stage mappings
- rewrites all links in the gnav
- removes sales force domain rewriting from personalization
- adds unit tests
Before: [https://stage--dme-partners--adobecom.hlx.live/channelpartners/home/](https://stage--dme-partners--adobecom.hlx.live/channelpartners/home/)
After: https://mwpw-163532-env-specific-links--dme-partners--adobecom.hlx.live/channelpartners/home/

MWPW-163532 - environment-specific partner finder gnav links

---

nala/blocks/signin/signin.spec.js
nala/blocks/signin/signin.test.js

Covers error page test cases (IDs: 17, 18, 19) defined in [Sign In Tests](https://wiki.corp.adobe.com/display/WEBT/MAPC+Sign+in+testing)
After: [https://MWPW-163152-error-pages-tests--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off](https://MWPW-163152-error-pages-tests--dme-partners--adobecom.hlx.live/channelpartners/?georouting=off)

New: added error pages nala tests

---

edsdme/blocks/pricelist/PricelistBlock.js

https://jira.corp.adobe.com/browse/MWPW-164313
- reads the pricelist filename property for setting up the download attribute
depends on https://git.corp.adobe.com/wcms/dx-partners-runtime/pull/128
https://mwpw-164313-pricelist-download-csv--dme-partners--adobecom.hlx.live/latam/channelpartners/drafts/automation/regression/pricelist

MWPW-164313 - Pricelists are downloaded as .txt files instead of .csv

---

edsdme/blocks/pricelist/PricelistBlockStyles.js
edsdme/components/PartnerCardsStyles.js

test url:
https://mwpw-164342-load-more-button-style--dme-partners--adobecom.hlx.live/latam/channelpartners/drafts/automation/regression/pricelist

MWPW-164342-apply on hover only when possible to hover

---

edsdme/blocks/search-full/SearchCardsStyles.js
edsdme/components/PartnerCardsStyles.js

Ticket: https://jira.corp.adobe.com/browse/MWPW-165153
There was ticket for `asset language` https://jira.corp.adobe.com/browse/MWPW-162444 and it had design for sidebar filter to be wider. This ticket was related to Search component
These changes include:
- reverting width of filters on Announcements (and other) component as it was before 204px
- setting width on sidebar filter only for Search component to 269px as it was in design in the ticket
Testing urls:
- https://mwpw-165153-cards-displayed--dme-partners--adobecom.hlx.page/channelpartners/home/search/
- https://mwpw-165153-cards-displayed--dme-partners--adobecom.hlx.page/channelpartners/home/announcements/

Fixing Announcments display

---

nala/blocks/region-selectors/region-selectors.page.js
nala/blocks/region-selectors/region-selectors.spec.js
nala/blocks/smoke-test/smoke.page.js
nala/blocks/smoke-test/smoke.spec.js
nala/blocks/smoke-test/smoke.test.js

ticket link: https://jira.corp.adobe.com/browse/MWPW-164551
testing url: https://mwpw-164551-smoke-tests--dme-partners--adobecom.hlx.page/channelpartners/

Smoke Tests

---

edsdme/scripts/links.js
edsdme/scripts/rewriteLinks.js
test/scripts/links.jest.js
test/scripts/rewriteLinks.jest.js

test url:
https://MWPW-164941-localize-links--dme-partners--adobecom.hlx.page/na/channelpartners/home/
Refactored existing link updates and added logic for locale udpate.
Summary of link updates :
A . Updates on stage:
1) domain update (for domains that are in map, to transform prod to stage links)
2) locale update (for domians that have configs with locale maps)
3) cbconnection login path link update ( only if user is signed in)
B. Updates on prod:
1) locale update (for domains that have configs with locale maps)
2) cbconnection login path link update ( only if user is signed in)

Mwpw 164941 localize links

---

edsdme/scripts/rewriteLinks.js

https://jira.corp.adobe.com/browse/MWPW-166435
- allows defining locale rewritters in domain configs
- provides `pathPrefix` and `queryParam` default rewritters
- adds config for salesforce
- adds `acomDomainConfig` for reuse
- swaps salesforce prod to stage domain mapping
Test URL:
https://MWPW-166435-partner-finder-localization--dme-partners--adobecom.hlx.page/na/channelpartners/enrollment/

MWPW-166435 - handle partner finder localization through code

---

edsdme/scripts/personalization.js

https://jira.corp.adobe.com/browse/MWPW-167119
- replaces regex lookbehind with group capture
- lookbehind browser support: https://caniuse.com/?search=lookbehind (reason why this wasn't working on older versions of Safari)
Test URL:
https://MWPW-167119-regex-older-support--dme-partners--adobecom.hlx.page/channelpartners/home/

MWPW-167119 - channelpartner is broken on iOS15 on XCode simulator

---

edsdme/blocks/partners-navigation/features/breadcrumbs/breadcrumbs.js
edsdme/blocks/partners-navigation/features/profile/dropdown.js
edsdme/blocks/partners-navigation/features/search/gnav-search.js
edsdme/blocks/partners-navigation/partners-navigation.js
edsdme/blocks/partners-navigation/utilities/utilities.js

resolves: https://jira.corp.adobe.com/browse/MWPW-167030 
follow up for: https://github.com/adobecom/milo/pull/3591 
DO NOT MERGE UNTIL ABOVE PR IS MERGED
test url: 
https://MWPW-167030-federatedjs--dme-partners--adobecom.hlx.page/channelpartners/home/
test url with milo libs from above pr : 
https://mwpw-167030-federatedjs--dme-partners--adobecom.hlx.page/channelpartners/home/?milolibs=move-federal-code--milo--mokimo

MWPW-167030-follow up for milo refactoring of federals

---

edsdme/components/SearchCard.js
edsdme/img/icons/announcement.svg

https://jira.corp.adobe.com/browse/MWPW-162728
depends on runtime PR: https://git.corp.adobe.com/wcms/dx-partners-runtime/pull/216 
- adds announcement icon
- adds announcement to list of supported file types
URL: https://MWPW-162728-announcements-icon--dme-partners--adobecom.aem.page/channelpartners/home/search/

MWPW-162728 - Announcements should have separate icon

---

edsdme/blocks/utils/utils.js
edsdme/scripts/scripts.js
edsdme/scripts/utils.js
tools/sidekick/config.json

adding sidekick event listener for previewing and publishing announcements and calling runtime action
removing prodHosts from scripts.js since its exported in utils.js
test url:
https://mwpw-172830-announcements--dme-partners--adobecom.aem.page/channelpartners/

adding sidekick event listener for previewing and publishing 
